[package]
name = "rust_lib_and_bin"
version = "0.2.0"
authors = ["Alan C <argot@digikata.com>"]
edition = "2018"

[lib]
name = "thelib"
path = "src/lib.rs"


[[bin]]
name = "mfbin"
path = "src/bin/multi-file-bin/bin.rs"

[dependencies]
